# This file is used for automated tests with Travis CI : travis-ci.org
# based on the template version 1
# the templates are availables in the documentation on http://docs.domogik.org/domogik/dev/en/package_development/plugins/tests/travis_templates.html
python:
  - "2.7"
  - "3.3"
mysql:
  adapter: mysql2
  database: domogik
  username: travis
  encoding: utf8
env:
  DMG_BRANCH=0.4-candidate
  DMG_PLUGIN=rfxcom
install:
  - cd ~
  - git clone https://github.com/domogik/domogik.git
  - cd domogik
  - git checkout $DMG_BRANCH
  - ~/domogik/src/domogik/tests/travis/travis-install-dependencies.sh
before_script:
  - ~/domogik/src/domogik/tests/travis/travis-setup-database.sh
  - ~/domogik/src/domogik/tests/travis/travis-install-domogik.sh
  - ~/domogik/src/domogik/tests/travis/travis-install-plugin.sh
  - ~/domogik/src/domogik/tests/travis/travis-start-domogik.sh
script:
  - cd $TRAVIS_BUILD_DIR
  - python tests/352_type52_temperarature_and_humidity_sensors.py
after_script:
  - ~/domogik/src/domogik/tests/travis/travis-after-failure.sh
after_failure:
  - ~/domogik/src/domogik/tests/travis/travis-after-failure.sh
notifications:
  irc: "irc.freenode.net#domogik"
  on_success: never
  on_failure: always
